apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion
  labels:
    app: aplicacion
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: aplicacion
  template:
    metadata:
      labels:
        app: aplicacion
        app.kubernetes.io/name: aplicacion
        app.kubernetes.io/instance: aplicacion
    spec:
      containers:
        - name: aplicacion
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          env:
            - name: TZ
              value: America/Santiago
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
